const TEAM_FLAG_CODES = new Map(
  Object.entries({
    가나: 'gh',
    남아공: 'za',
    네덜란드: 'nl',
    노르웨이: 'no',
    뉴질랜드: 'nz',
    대한민국: 'kr',
    독일: 'de',
    멕시코: 'mx',
    모로코: 'ma',
    미국: 'us',
    벨기에: 'be',
    보스니아: 'ba',
    브라질: 'br',
    사우디: 'sa',
    세네갈: 'sn',
    스웨덴: 'se',
    스위스: 'ch',
    스코틀랜드: 'gb-sct',
    스페인: 'es',
    아르헨: 'ar',
    아르헨티나: 'ar',
    아이티: 'ht',
    알제리: 'dz',
    에콰도르: 'ec',
    오스트리아: 'at',
    요르단: 'jo',
    우루과이: 'uy',
    우즈벡: 'uz',
    우즈베키스탄: 'uz',
    이라크: 'iq',
    이란: 'ir',
    이집트: 'eg',
    일본: 'jp',
    잉글랜드: 'gb-eng',
    체코: 'cz',
    카보베르: 'cv',
    카타르: 'qa',
    캐나다: 'ca',
    코스타리카: 'cr',
    코트디: 'ci',
    코트디부아르: 'ci',
    콜롬비아: 'co',
    콩고: 'cd',
    퀴라소: 'cw',
    크로아티아: 'hr',
    튀니지: 'tn',
    튀르키예: 'tr',
    터키: 'tr',
    파나마: 'pa',
    파라과이: 'py',
    포르투갈: 'pt',
    프랑스: 'fr',
    호주: 'au',
  }),
);

export const getTeamFlagCode = (teamName: string) => TEAM_FLAG_CODES.get(teamName.trim());

export const getTeamFlagSrc = (teamName: string) => {
  const flagCode = getTeamFlagCode(teamName);

  return flagCode ? `${import.meta.env.BASE_URL}flags/${flagCode}.svg` : undefined;
};
